steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'resume/Infrastructure'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'resume/Infrastructure'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'runWorkflowFunction', '--trigger-http', '--runtime', 'nodejs12', '--entry-point', 'runWorkflowFunction']
  dir: 'resume/Infrastructure'
options:
  logging: CLOUD_LOGGING_ONLY
