steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'runWorkflowFunction', '--source=.', '--trigger-http', '--runtime=nodejs12', '--entry-point', 'runWorkflow', '--allow-unauthenticated']
  dir: 'Infrastructure'
options:
  logging: CLOUD_LOGGING_ONLY
env: 'us-west1'
