steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'runWorkflowFunction', '--source=.', '--trigger-http', '--runtime=nodejs12', '--entry-point', 'runWorkflow', '--allow-unauthenticated', '--region', 'us-west1']
   env:
   - name: LOG_LEVEL
     value: verbose
  dir: 'Infrastructure'
options:
  logging: CLOUD_LOGGING_ONLY

